name: "Hello World Python Action"
description: " A simpple GitHub Action that prints 'Hello World!' using Python."
author: "Arman Asgharpoor"

inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"

outputs:
  time:
    description: "The time we greeted you"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}

branding:
  icon: "terminal"
  color: "blue"
